// Honest attribution wording. CORRELATED must never read as "generated by".
export function attributionLabel(strength: string | null | undefined): string {
  switch (strength) {
    case "DIRECT":
      return "direct";
    case "ATTRIBUTED":
      return "attributed (last-touch)";
    case "EXPERIMENTAL":
      return "experiment-backed";
    case "CORRELATED":
      return "correlated — not causal";
    case "UNKNOWN":
      return "unknown";
    default:
      return "—";
  }
}
