import { z } from "zod";

// ---------------------------------------------------------------------------
// M9 — Measurement, Attribution & Feedback Loop contracts.
// Brand-agnostic: nothing here assumes a product category, channel mix or
// currency. Numbers are always deterministic; Claude only explains them.
// ---------------------------------------------------------------------------

export const RecommendationStatusSchema = z.enum([
  "PROPOSED",
  "APPROVED",
  "REJECTED",
  "EXECUTED",
  "MEASURING",
  "MEASURED",
  "EXPIRED",
  "FAILED",
]);

export const RejectionReasonSchema = z.enum([
  "NOT_RELEVANT",
  "BAD_TIMING",
  "BRAND_MISMATCH",
  "TOO_EXPENSIVE",
  "TOO_RISKY",
  "ALREADY_PLANNED",
  "OTHER",
]);

// How strongly an observed result is tied to the action that supposedly
// caused it. CORRELATED must never be presented as "generated by".
export const AttributionStrengthSchema = z.enum([
  "DIRECT",
  "ATTRIBUTED",
  "EXPERIMENTAL",
  "CORRELATED",
  "UNKNOWN",
]);

export const MeasurementDataQualitySchema = z.enum([
  "COMPLETE",
  "PARTIAL",
  "STALE",
  "INSUFFICIENT",
  "UNAVAILABLE",
]);

export const OutcomeClassificationSchema = z.enum([
  "OUTPERFORMED",
  "EXPECTED",
  "UNDERPERFORMED",
  "INCONCLUSIVE",
]);

export const OutcomeDimensionSchema = z.enum([
  "REACH",
  "ENGAGEMENT",
  "TRAFFIC",
  "LEADS",
  "CONVERSIONS",
  "REVENUE",
  "PROFIT",
  "RETENTION",
  "AOV",
  "RECOVERY",
  "SUBSCRIPTIONS",
  "OTHER",
]);

// Generic value units — commerce uses store currency, but a Brand may measure
// counts, percentages, durations or scores instead of money.
export const ValueUnitSchema = z.enum([
  "CURRENCY",
  "PERCENTAGE",
  "COUNT",
  "DURATION",
  "SCORE",
  "OTHER",
]);

export const RecommendationTypeSchema = z.enum([
  "CREATE_CONTENT",
  "PUBLISH_CONTENT",
  "REVIEW_CONTENT",
  "RECOVER_ABANDONED",
  "RUN_EXPERIMENT",
  "REVIEW_SEGMENT",
  "FIX_CONNECTION",
  "INVESTIGATE",
  "OTHER",
]);

export const EvidenceRefSchema = z.object({
  source: z.string(),
  refType: z.string(),
  refId: z.string().nullable(),
  note: z.string().nullable(),
});

export const OutcomeMetricSchema = z.object({
  id: z.string(),
  dimension: OutcomeDimensionSchema,
  metric: z.string(),
  value: z.number(),
  unit: ValueUnitSchema,
  currencyCode: z.string().nullable(),
  baseline: z.number().nullable(),
  delta: z.number().nullable(),
  deltaPct: z.number().nullable(),
  source: z.string(),
  attributionStrength: AttributionStrengthSchema,
  dataQuality: MeasurementDataQualitySchema,
  observedAt: z.coerce.date(),
});

export const RecommendationSchema = z.object({
  id: z.string(),
  brandId: z.string(),
  type: z.string(),
  title: z.string(),
  rationale: z.string(),
  evidenceRefs: z.array(EvidenceRefSchema),
  confidence: z.number().min(0).max(1),
  expectedImpact: z.string().nullable(),
  expectedImpactValue: z.number().nullable(),
  expectedImpactUnit: ValueUnitSchema.nullable(),
  targetType: z.string().nullable(),
  targetId: z.string().nullable(),
  actionClass: z.enum(["READ", "PROPOSE", "MUTATE", "EXECUTE"]),
  status: RecommendationStatusSchema,
  rejectionReason: RejectionReasonSchema.nullable(),
  rejectionNote: z.string().nullable(),
  decidedAt: z.coerce.date().nullable(),
  executedAt: z.coerce.date().nullable(),
  measurementWindowDays: z.number(),
  measurementWindowEndsAt: z.coerce.date().nullable(),
  measuredAt: z.coerce.date().nullable(),
  outcome: OutcomeClassificationSchema.nullable(),
  outcomeSummary: z.string().nullable(),
  attributionStrength: AttributionStrengthSchema.nullable(),
  dataQuality: MeasurementDataQualitySchema.nullable(),
  createdAt: z.coerce.date(),
});

export const DecideRecommendationSchema = z.object({
  status: z.enum(["APPROVED", "REJECTED"]),
  rejectionReason: RejectionReasonSchema.optional(),
  rejectionNote: z.string().max(500).optional(),
});

// ---------------------------------------------------------------------------
// UTM / campaign tracking. Deterministic naming — Claude never invents
// attribution parameters. Original destination URLs are preserved.
// ---------------------------------------------------------------------------

export const UtmParamsSchema = z.object({
  utm_source: z.string(),
  utm_medium: z.string(),
  utm_campaign: z.string(),
  utm_content: z.string().optional(),
});

// ---------------------------------------------------------------------------
// Experiments
// ---------------------------------------------------------------------------

export const ExperimentEvaluationStateSchema = z.enum([
  "INSUFFICIENT_DATA",
  "DIRECTIONAL",
  "WINNER",
  "NO_CLEAR_WINNER",
  "STOPPED",
]);

export const ExperimentVariantResultSchema = z.object({
  variantId: z.string(),
  variantName: z.string(),
  isControl: z.boolean(),
  assigned: z.number(),
  converted: z.number(),
  conversionRate: z.number().nullable(),
  totalRevenue: z.number(),
  totalContributionProfit: z.number(),
  totalIncentiveCost: z.number(),
  avgProfitPerAssigned: z.number().nullable(),
});

export const ExperimentEvaluationSchema = z.object({
  experimentId: z.string(),
  name: z.string(),
  status: z.string(),
  state: ExperimentEvaluationStateSchema,
  minSamplePerVariant: z.number(),
  control: ExperimentVariantResultSchema.nullable(),
  variants: z.array(ExperimentVariantResultSchema),
  // Best non-control variant vs control, on contribution profit per assigned.
  bestVariantId: z.string().nullable(),
  profitDeltaPerAssigned: z.number().nullable(),
  note: z.string(),
});

// ---------------------------------------------------------------------------
// CMO effectiveness scorecard — no fake universal "AI score".
// ---------------------------------------------------------------------------

export const CmoScorecardSchema = z.object({
  generatedAt: z.coerce.date(),
  windowDays: z.number(),
  proposed: z.number(),
  approved: z.number(),
  rejected: z.number(),
  executed: z.number(),
  measuring: z.number(),
  measured: z.number(),
  expired: z.number(),
  failed: z.number(),
  approvalRate: z.number().nullable(),
  executionRate: z.number().nullable(),
  measurementCoverage: z.number().nullable(),
  outcomes: z.object({
    outperformed: z.number(),
    expected: z.number(),
    underperformed: z.number(),
    inconclusive: z.number(),
  }),
  rejectionReasons: z.record(z.number()),
  currencyCode: z.string().nullable(),
  attributedValue: z.number(),
  experimentBackedIncrementalValue: z.number(),
});

// ---------------------------------------------------------------------------
// Weekly CMO review — deterministic aggregation first, interpretation after.
// ---------------------------------------------------------------------------

export const WeeklyRecommendationHighlightSchema = z.object({
  recommendationId: z.string(),
  title: z.string(),
  type: z.string(),
  outcome: OutcomeClassificationSchema.nullable(),
  attributionStrength: AttributionStrengthSchema.nullable(),
  dataQuality: MeasurementDataQualitySchema.nullable(),
  summary: z.string().nullable(),
});

export const WeeklyReviewSchema = z.object({
  generatedAt: z.coerce.date(),
  brandName: z.string().nullable(),
  periodStart: z.coerce.date(),
  periodEnd: z.coerce.date(),
  business: z.object({
    status: z.enum(["AVAILABLE", "STALE", "UNAVAILABLE", "NOT_CONFIGURED"]),
    currencyCode: z.string().nullable(),
    revenue: z.number().nullable(),
    orderCount: z.number().nullable(),
    aov: z.number().nullable(),
    previousRevenue: z.number().nullable(),
    revenueDeltaPct: z.number().nullable(),
  }),
  content: z.object({
    published: z.number(),
    failedPublications: z.number(),
    measured: z.number(),
    outperformed: z.number(),
    expected: z.number(),
    underperformed: z.number(),
    inconclusive: z.number(),
  }),
  market: z.object({
    newOpportunities: z.number(),
    briefsCreated: z.number(),
  }),
  revenue: z.object({
    currencyCode: z.string().nullable(),
    attributedRevenue: z.number(),
    attributedProfit: z.number(),
    incentiveCost: z.number(),
    incrementalEstimate: z.number(),
    recoveredOrders: z.number(),
  }),
  experiments: z.array(ExperimentEvaluationSchema),
  recommendations: z.object({
    proposed: z.number(),
    approved: z.number(),
    rejected: z.number(),
    executed: z.number(),
    measured: z.number(),
    unmeasured: z.number(),
    failedExecutions: z.number(),
    wins: z.array(WeeklyRecommendationHighlightSchema),
    losses: z.array(WeeklyRecommendationHighlightSchema),
    inconclusive: z.array(WeeklyRecommendationHighlightSchema),
  }),
  interpretation: z.object({
    status: z.enum(["AVAILABLE", "UNAVAILABLE"]),
    headline: z.string().nullable(),
    narrative: z.string().nullable(),
    failureReason: z.string().nullable(),
  }),
});

// ---------------------------------------------------------------------------
// Today "Recent Results" — only real measured data, never fabricated examples.
// ---------------------------------------------------------------------------

export const TodayRecentResultsSchema = z.object({
  status: z.enum(["AVAILABLE", "UNAVAILABLE"]),
  measuredLast7: z.number(),
  outperformed: z.number(),
  expected: z.number(),
  underperformed: z.number(),
  inconclusive: z.number(),
  currencyCode: z.string().nullable(),
  attributedProfitLast7: z.number().nullable(),
  highlights: z.array(WeeklyRecommendationHighlightSchema),
  directionalExperiments: z.array(
    z.object({
      experimentId: z.string(),
      name: z.string(),
      state: ExperimentEvaluationStateSchema,
    }),
  ),
});

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type RecommendationStatus = z.infer<typeof RecommendationStatusSchema>;
export type RejectionReason = z.infer<typeof RejectionReasonSchema>;
export type AttributionStrength = z.infer<typeof AttributionStrengthSchema>;
export type MeasurementDataQuality = z.infer<
  typeof MeasurementDataQualitySchema
>;
export type OutcomeClassification = z.infer<typeof OutcomeClassificationSchema>;
export type OutcomeDimension = z.infer<typeof OutcomeDimensionSchema>;
export type ValueUnit = z.infer<typeof ValueUnitSchema>;
export type RecommendationType = z.infer<typeof RecommendationTypeSchema>;
export type EvidenceRef = z.infer<typeof EvidenceRefSchema>;
export type OutcomeMetric = z.infer<typeof OutcomeMetricSchema>;
export type Recommendation = z.infer<typeof RecommendationSchema>;
export type DecideRecommendation = z.infer<typeof DecideRecommendationSchema>;
export type UtmParams = z.infer<typeof UtmParamsSchema>;
export type ExperimentEvaluationState = z.infer<
  typeof ExperimentEvaluationStateSchema
>;
export type ExperimentVariantResult = z.infer<
  typeof ExperimentVariantResultSchema
>;
export type ExperimentEvaluation = z.infer<typeof ExperimentEvaluationSchema>;
export type CmoScorecard = z.infer<typeof CmoScorecardSchema>;
export type WeeklyRecommendationHighlight = z.infer<
  typeof WeeklyRecommendationHighlightSchema
>;
export type WeeklyReview = z.infer<typeof WeeklyReviewSchema>;
export type TodayRecentResults = z.infer<typeof TodayRecentResultsSchema>;
