"use client";

import { useCallback, useEffect, useState } from "react";
import {
  card,
  EmptyState,
  fmtDate,
  PageHeader,
  sectionLabel,
  StatusBadge,
} from "../components/ui";
import WhatsAppTabs from "./WhatsAppTabs";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";

interface Conversation {
  id: string;
  chatId: string;
  displayName: string | null;
  phone: string | null;
  contactId: string | null;
  lastMessageAt: string | null;
  lastMessagePreview: string | null;
  unreadCount: number;
}

interface Message {
  id: string;
  providerMessageId: string;
  direction: "INBOUND" | "OUTBOUND";
  origin: "INBOUND" | "OWNER_MANUAL" | "AUTOMATION" | "BROADCAST";
  body: string;
  deliveryState: string;
  timestamp: string;
}

/** Colour-codes who actually sent a message (invariant 13). */
const ORIGIN_STYLES: Record<string, { bg: string; label: string }> = {
  INBOUND: { bg: "#f2f2f0", label: "Customer" },
  OWNER_MANUAL: { bg: "#e8f0fb", label: "You" },
  AUTOMATION: { bg: "#f0e8fb", label: "Automation" },
  BROADCAST: { bg: "#f0e8fb", label: "Broadcast" },
};

export default function WhatsAppInboxPage() {
  const [conversations, setConversations] = useState<Conversation[] | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [reply, setReply] = useState("");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [syncing, setSyncing] = useState(false);

  const loadConversations = useCallback(async () => {
    try {
      const res = await fetch(`${API}/whatsapp/conversations`);
      setConversations(await res.json());
    } catch (e: any) {
      setError(e.message);
      setConversations([]);
    }
  }, []);

  useEffect(() => {
    loadConversations();
  }, [loadConversations]);

  async function openConversation(id: string) {
    setSelected(id);
    setError(null);
    try {
      const res = await fetch(`${API}/whatsapp/conversations/${id}`);
      const body = await res.json();
      setMessages(body.messages ?? []);
    } catch (e: any) {
      setError(e.message);
    }
  }

  async function sync() {
    setSyncing(true);
    setError(null);
    try {
      const res = await fetch(`${API}/whatsapp/conversations/sync`, {
        method: "POST",
      });
      const body = await res.json();
      if (!res.ok) throw new Error(body?.message ?? "Sync failed");
      await loadConversations();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setSyncing(false);
    }
  }

  async function send() {
    if (!selected || !reply.trim()) return;
    setSending(true);
    setError(null);
    try {
      const res = await fetch(`${API}/whatsapp/conversations/${selected}/reply`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ body: reply }),
      });
      const body = await res.json();
      if (!res.ok) throw new Error(body?.message ?? "Send failed");
      setReply("");
      await openConversation(selected);
      await loadConversations();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setSending(false);
    }
  }

  return (
    <>
      <PageHeader
        title="WhatsApp — Inbox"
        subtitle="Replies you send here are manual and are never generated by the CMO."
        right={
          <button
            onClick={sync}
            disabled={syncing}
            style={{
              padding: "0.45rem 0.9rem",
              borderRadius: 6,
              border: "1px solid #ccc",
              background: "#fff",
              fontSize: "0.82rem",
              fontWeight: 600,
              cursor: syncing ? "default" : "pointer",
            }}
          >
            {syncing ? "Syncing…" : "Sync conversations"}
          </button>
        }
      />
      <WhatsAppTabs active="inbox" />

      {error && (
        <div style={{ ...card, background: "#fbe8e8", marginBottom: "1rem" }}>
          <p style={{ fontSize: "0.82rem", color: "#7a2020" }}>{error}</p>
        </div>
      )}

      {conversations === null ? (
        <p style={{ color: "#888" }}>Loading…</p>
      ) : conversations.length === 0 ? (
        <EmptyState
          message="No conversations yet."
          hint="Connect WhatsApp, then use Sync conversations to pull your chat list."
        />
      ) : (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "minmax(220px, 320px) 1fr",
            gap: "1rem",
            alignItems: "start",
          }}
        >
          <div style={{ display: "grid", gap: "0.4rem" }}>
            {conversations.map((c) => (
              <button
                key={c.id}
                onClick={() => openConversation(c.id)}
                style={{
                  ...card,
                  textAlign: "left",
                  cursor: "pointer",
                  padding: "0.7rem 0.85rem",
                  border:
                    selected === c.id ? "2px solid #1a1a1a" : "1px solid #e5e5e5",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    gap: "0.5rem",
                  }}
                >
                  <strong style={{ fontSize: "0.85rem" }}>
                    {c.displayName ?? c.phone ?? c.chatId}
                  </strong>
                  {c.unreadCount > 0 && (
                    <span
                      style={{
                        background: "#1a7a3d",
                        color: "#fff",
                        borderRadius: 999,
                        fontSize: "0.68rem",
                        fontWeight: 700,
                        padding: "0.05rem 0.4rem",
                      }}
                    >
                      {c.unreadCount}
                    </span>
                  )}
                </div>
                <div
                  style={{
                    fontSize: "0.75rem",
                    color: "#888",
                    marginTop: "0.2rem",
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    whiteSpace: "nowrap",
                  }}
                >
                  {c.lastMessagePreview ?? "—"}
                </div>
                <div
                  style={{ fontSize: "0.7rem", color: "#aaa", marginTop: "0.2rem" }}
                >
                  {fmtDate(c.lastMessageAt)}
                </div>
              </button>
            ))}
          </div>

          <div style={card}>
            {!selected ? (
              <p style={{ color: "#888", fontSize: "0.85rem" }}>
                Select a conversation.
              </p>
            ) : (
              <>
                <div style={sectionLabel}>Messages</div>
                <div
                  style={{
                    display: "grid",
                    gap: "0.5rem",
                    maxHeight: 460,
                    overflowY: "auto",
                    marginBottom: "0.9rem",
                  }}
                >
                  {messages.length === 0 && (
                    <p style={{ color: "#888", fontSize: "0.82rem" }}>
                      No messages stored for this conversation yet.
                    </p>
                  )}
                  {messages.map((m) => {
                    const style =
                      ORIGIN_STYLES[m.origin] ?? ORIGIN_STYLES.INBOUND!;
                    return (
                      <div
                        key={m.id}
                        style={{
                          background: style.bg,
                          borderRadius: 8,
                          padding: "0.55rem 0.7rem",
                          maxWidth: "80%",
                          marginLeft:
                            m.direction === "OUTBOUND" ? "auto" : undefined,
                        }}
                      >
                        <div
                          style={{
                            fontSize: "0.66rem",
                            fontWeight: 700,
                            color: "#666",
                            marginBottom: "0.2rem",
                            letterSpacing: "0.04em",
                          }}
                        >
                          {style.label.toUpperCase()}
                        </div>
                        <div style={{ fontSize: "0.85rem", whiteSpace: "pre-wrap" }}>
                          {m.body}
                        </div>
                        <div
                          style={{
                            fontSize: "0.68rem",
                            color: "#999",
                            marginTop: "0.25rem",
                          }}
                        >
                          {fmtDate(m.timestamp)}
                          {m.direction === "OUTBOUND" && ` · ${m.deliveryState}`}
                        </div>
                      </div>
                    );
                  })}
                </div>

                <div style={{ display: "flex", gap: "0.5rem" }}>
                  <input
                    value={reply}
                    onChange={(e) => setReply(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && !e.shiftKey) send();
                    }}
                    placeholder="Type a reply — sent as you, not as the CMO"
                    style={{
                      flex: 1,
                      padding: "0.5rem 0.7rem",
                      border: "1px solid #ccc",
                      borderRadius: 6,
                      fontSize: "0.85rem",
                    }}
                  />
                  <button
                    onClick={send}
                    disabled={sending || !reply.trim()}
                    style={{
                      padding: "0.5rem 1rem",
                      borderRadius: 6,
                      border: "none",
                      background: sending || !reply.trim() ? "#999" : "#1a1a1a",
                      color: "#fff",
                      fontSize: "0.85rem",
                      fontWeight: 600,
                      cursor: sending || !reply.trim() ? "default" : "pointer",
                    }}
                  >
                    {sending ? "Sending…" : "Send"}
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
}
